name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      run: git clone https://github.com/nodejs/examples.git

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: change dir
      run: cd examples

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
